version: '3.8'

services:
  server:
    container_name: server-app
    image: server
    build: ./server
    command: /bin/sh entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
      - /server/app/node_modules
    networks:
      - app_network
  client:
    container_name: client-app
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - 3001:3001
    volumes:
      - ./client:/app
      - /client/app/node_modules
    networks:
      - app_network
    stdin_open: true
    tty: true
  db:
    image: mysql:8.0
    container_name: db-app
    environment:
      MYSQL_DATABASE: webdb
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_HOST: localhost
    ports:
      - '3308:3306'
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
